cruding:
  entity_class_alias_map:
    page: App\Paging\Entity\Page
    page-revision: App\Paging\Entity\PageRevision
    page-publication: App\Paging\Entity\PagePublication
    page-grant: App\Paging\Entity\PageGrant
    page-acceptance: App\Paging\Entity\PageAcceptance
  form_type_map:
    App\Paging\Entity\Page: App\Paging\Form\PageForm
    App\Paging\Entity\PageRevision: App\Paging\Form\PageRevisionForm
    App\Paging\Entity\PagePublication: App\Paging\Form\PagePublicationForm

  route_guard:
    require_runtime_lock: false
