doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    profiling_collect_backtrace: '%kernel.debug%'
    mapping_types:
      ltree: string
  orm:
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
    mappings:
      Paging:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Paging\Entity'
        alias: Paging
      ObjectingEmbeddable:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/vendor/objecting/object/src/Embeddable'
        prefix: 'App\Objecting\Embeddable'
