<?php

declare(strict_types=1);

namespace App\Paging\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260914090500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Normalize Objecting system columns to entity-native names.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Migration can only be executed safely on PostgreSQL.');

        $this->addSql('UPDATE page SET slug = object_slug WHERE object_slug IS NOT NULL');
        $this->addSql('UPDATE page SET status = object_status WHERE object_status IS NOT NULL');

        $this->addSql('DROP INDEX IF EXISTS page_object_uuid_uq');
        $this->addSql('DROP INDEX IF EXISTS page_object_slug_uq');

        $this->addSql('ALTER TABLE page RENAME COLUMN object_uuid TO uuid');
        $this->addSql('ALTER TABLE page DROP COLUMN object_slug');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_first_title TO first_title');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_middle_title TO middle_title');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_last_title TO last_title');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_created_at TO created_at');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_modified_at TO modified_at');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_created_by TO created_by');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_modified_by TO modified_by');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_active TO active');
        $this->addSql('ALTER TABLE page RENAME COLUMN object_enabled TO enabled');
        $this->addSql('ALTER TABLE page DROP COLUMN object_status');
        $this->addSql('ALTER TABLE page ALTER COLUMN slug TYPE VARCHAR(190)');
        $this->addSql('ALTER TABLE page ALTER COLUMN status TYPE VARCHAR(64)');
        $this->addSql('ALTER TABLE page ALTER COLUMN status DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX page_uuid_uq ON page (uuid)');
        $this->addSql('ALTER TABLE page ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE page ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX page_uuid_uq RENAME TO UNIQ_140AB620D17F50A6');
        $this->addSql('ALTER INDEX idx_page_current_revision RENAME TO IDX_140AB620A32ED756');
        $this->addSql('ALTER INDEX idx_page_published_revision RENAME TO IDX_140AB620FE671D30');
        $this->addSql("COMMENT ON COLUMN page_acceptance.accepted_at IS ''");
        $this->addSql("COMMENT ON COLUMN page_attachment_reference.created_at IS ''");
        $this->addSql("COMMENT ON COLUMN page_publication.published_at IS ''");
        $this->addSql("COMMENT ON COLUMN page_publication.effective_from IS ''");
        $this->addSql("COMMENT ON COLUMN page_publication.expires_at IS ''");
        $this->addSql("COMMENT ON COLUMN page_revision.created_at IS ''");
        $this->addSql("COMMENT ON COLUMN page_revision.locked_at IS ''");

        $this->addSql('ALTER TABLE page_grant RENAME COLUMN object_created_at TO created_at');
        $this->addSql('ALTER TABLE page_grant RENAME COLUMN object_modified_at TO modified_at');
        $this->addSql('ALTER TABLE page_grant RENAME COLUMN object_created_by TO created_by');
        $this->addSql('ALTER TABLE page_grant RENAME COLUMN object_modified_by TO modified_by');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Migration can only be executed safely on PostgreSQL.');

        $this->addSql("COMMENT ON COLUMN page_revision.locked_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN page_revision.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN page_publication.expires_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN page_publication.effective_from IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN page_publication.published_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN page_attachment_reference.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN page_acceptance.accepted_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER INDEX IDX_140AB620FE671D30 RENAME TO idx_page_published_revision');
        $this->addSql('ALTER INDEX IDX_140AB620A32ED756 RENAME TO idx_page_current_revision');
        $this->addSql('ALTER INDEX UNIQ_140AB620D17F50A6 RENAME TO page_uuid_uq');
        $this->addSql('ALTER TABLE page ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql("ALTER TABLE page ALTER id SET DEFAULT nextval('page_id_seq'::regclass)");

        $this->addSql('ALTER TABLE page_grant RENAME COLUMN created_at TO object_created_at');
        $this->addSql('ALTER TABLE page_grant RENAME COLUMN modified_at TO object_modified_at');
        $this->addSql('ALTER TABLE page_grant RENAME COLUMN created_by TO object_created_by');
        $this->addSql('ALTER TABLE page_grant RENAME COLUMN modified_by TO object_modified_by');

        $this->addSql('DROP INDEX IF EXISTS page_uuid_uq');
        $this->addSql('ALTER TABLE page RENAME COLUMN uuid TO object_uuid');
        $this->addSql('ALTER TABLE page ADD object_slug VARCHAR(190) DEFAULT NULL');
        $this->addSql('UPDATE page SET object_slug = slug');
        $this->addSql('ALTER TABLE page ALTER COLUMN object_slug SET NOT NULL');
        $this->addSql('ALTER TABLE page RENAME COLUMN first_title TO object_first_title');
        $this->addSql('ALTER TABLE page RENAME COLUMN middle_title TO object_middle_title');
        $this->addSql('ALTER TABLE page RENAME COLUMN last_title TO object_last_title');
        $this->addSql('ALTER TABLE page RENAME COLUMN created_at TO object_created_at');
        $this->addSql('ALTER TABLE page RENAME COLUMN modified_at TO object_modified_at');
        $this->addSql('ALTER TABLE page RENAME COLUMN created_by TO object_created_by');
        $this->addSql('ALTER TABLE page RENAME COLUMN modified_by TO object_modified_by');
        $this->addSql('ALTER TABLE page RENAME COLUMN active TO object_active');
        $this->addSql('ALTER TABLE page RENAME COLUMN enabled TO object_enabled');
        $this->addSql('ALTER TABLE page ADD object_status VARCHAR(64) DEFAULT NULL');
        $this->addSql('UPDATE page SET object_status = status');
        $this->addSql('ALTER TABLE page ALTER COLUMN slug TYPE VARCHAR(128)');
        $this->addSql('ALTER TABLE page ALTER COLUMN status TYPE VARCHAR(32)');
        $this->addSql('ALTER TABLE page ALTER COLUMN status SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX page_object_uuid_uq ON page (object_uuid)');
        $this->addSql('CREATE UNIQUE INDEX page_object_slug_uq ON page (object_slug)');
    }
}
